import 'package:flutter/material.dart';
import 'package:hexcolor/hexcolor.dart';

List <Color> colorList=[
  Colors.indigo,
  Colors.black,
  Colors.lightBlue,
  Colors.deepPurple,
  Colors.yellow,
  Colors.deepOrange,
  Colors.tealAccent,
  HexColor("#4DCC4E"),
  HexColor("#8C9CBE"),
  Colors.indigo,
  Colors.black,
  Colors.lightBlue,
  Colors.deepPurple,
  Colors.yellow,
  Colors.deepOrange,
  Colors.tealAccent,
  HexColor("#4DCC4E"),
  HexColor("#8C9CBE"),
  Colors.indigo,
  Colors.black,
  Colors.lightBlue,
  Colors.deepPurple,
  Colors.yellow,
  Colors.deepOrange,
  Colors.tealAccent,
  HexColor("#4DCC4E"),
  HexColor("#8C9CBE"),
  Colors.indigo,
  Colors.black,
  Colors.lightBlue,
  Colors.deepPurple,
  Colors.yellow,
  Colors.deepOrange,
  Colors.tealAccent,
  HexColor("#4DCC4E"),
  HexColor("#8C9CBE"),
];